name: 
on:
  push:
    branches:
      - master

jobs:
  my-job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: setup gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CRED_JSON }}
      - name: config gcp account
        run: gcloud config set account ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - name: Download newest image
        run: |
          gcloud compute ssh --zone "${{ secrets.GCP_ZONE }}" "master" --project "${{ secrets.GCP_PROJECT }}"  --command "git clone https://github.com/kristiyanyanchev/learnk8s.git && "kubectl apply -f deployment.yaml"