name: 
on:
  push:
    branches:
      - master

jobs:
  my-job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt large secret
        run: ./secrets/decrypt_secret.sh
        env:
          GCP_SECRET_PASSPHRASE: ${{ secrets.GCP_SECRET_PASSPHRASE }}
      - name: setup gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_file_path: ./secrets/gcp_secret.json
      - name: config gcp account
        run: gcloud config set account ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - name: Download newest image
        run: |
          gcloud compute ssh --zone "${{ secrets.GCP_ZONE }}" "master" --project "${{ secrets.GCP_PROJECT }}"  --command "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/open:latest"
