name: 
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: setup gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CRED_JSON }}

      - name: Download newest image
        run: |
          gcloud compute ssh --zone "${{ secrets.GCP_ZONE }}" "master" --project "${{ secrets.GCP_PROJECT }}"  --command "pwd && export KUBECONFIG=$HOME/.kube/config && cd learnk8s && git pull  && kubectl apply -f ../learnk8s --server=${{ secrets.SERVER_URL }}"