name: 
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Docker
        uses: actions/setup-docker@v2
        with:
          dockerfile: Dockerfile
          container-runtime: containerd
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies 
        run: 
          go get ./...
      - name: Build
        run: 
          go build -v ./...
      - name: Test
        run: 
          go test -v ./...
      - name: Docker build
        run: 
          docker build -t kristiyanyanchev/open:latest . 
      - name: Docker Push
        run: 
          docker push kristiyanyanchev/open:latest