name: 
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies 
        run: 
          go get ./...
      - name: Build
        run: 
          go build -v ./...
      - name: Test
        run: 
          go test -v ./...
      - name: Docker build
        run: 
          docker build -t kristiyanyanchev/open:latest . 
      - name: Docker Push
        run: 
          docker push kristiyanyanchev/open:latest